secret:
    enabled: ENC[AES256_GCM,data:CcUF6A==,iv:lsl8/gImKCr4IAQW9LZtt8zZIo2T+R6t6h38LPEjGjQ=,tag:fktCXKEJCXnzkbJIixnIIA==,type:bool]
    data:
        MCP_AUTH_TOKEN: ENC[AES256_GCM,data:MR1yLBnN+CBjKTZlIR9jyBwR9nd180/44u+CiKJlVVO+zCKHLXY0zIOibkJZZu1XcKF2JTMDSONcJrYKW08aUg==,iv:z4Mr2Yi0jhQtuSaaUYnNlL/ukYxBMxFrbHjOUbvPZ+Y=,tag:8UoKSHC+BWIc5Ze4H7e3FA==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/kitabisa/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-10-06T09:31:10Z"
          enc: CiQAGfyZWU9LnxA0ISje6RMDrFeAZ3PNCPVH/u5V9kFMwrkQSnoSSQBoVvUJpY2Yrwgoc/eXeZewHljL6IlyA+4FV+UMym7hQa5OOc73Xi3qOEGMqbV0MrsM/oay5mH3dMfZu5OazcnbCVhYjovyOeI=
    lastmodified: "2026-10-06T09:31:11Z"
    mac: ENC[AES256_GCM,data:ky0WyJJ3TnibbAecBT5nxL9PYiBbJkAAAjeJfh0AetkOZb1D3zSefY7AOc27ppHH2oLOuVPZz0OJtG02QMNAQIDfZskpaxDIvC7EbNVw+ySu5AU6cngW0Y8tlwW61aEtbj0nTIvumdEL8L0jmFOAsJAjnUfOtVJeFwNdeQ6R5gw=,iv:Lo0KHJj56aMESGLB71KoKrm5K8gqT99cn2UMJPL1esw=,tag:A26BUUkhH4kRmp2zYvsNcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
